spring.application.name=daemonops-sharemarket

server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/daemon_ops_exchange

spring.profiles.active=advaitya
spring.jpa.hibernate.ddl-auto=update