spring.application.name=company-management

server.port = 8081
spring.datasource.url=jdbc:postgresql://localhost:5432/daemon_ops
spring.datasource.username=postgres
spring.datasource.password=Var@d28

spring.jpa.hibernate.ddl-auto=update